DARK_NET_PATH = "lib/darknet/"
DARK_NET_LIB_MAC = DARK_NET_PATH + "lib_mac/"
DARK_NET_LIB_WIN = DARK_NET_PATH + "lib_win/"
DARK_NET_LIB_LINUX = DARK_NET_PATH + "lib_linux/"
DARK_NET_CFG_PATH = DARK_NET_PATH + "cfg/"


VIDEO_EXTRACT_OUTPUT_PATH = "./out/"
IMAGE_DETECT_INPUT_PATH = VIDEO_EXTRACT_OUTPUT_PATH
IMAGE_DETECT_OUTPUT_PATH = VIDEO_EXTRACT_OUTPUT_PATH + "out/"
